import_from_json:
  fields:
    path:
      required: true
      example: "/config/home_upkeep_import"
      selector:
        text:

import_from_addon:
  fields:
    docs:
      required: true
      example: '[{"version": 1, "list": {...}, "tasks": [...]}]'
      selector:
        object:
    overwrite_list_ids:
      required: false
      example: "[1, 2]"
      selector:
        object:
