import_from_api:
  fields:
    base_url:
      required: true
      example: "http://homeassistant.local:8125"
      selector:
        text:

import_from_json:
  fields:
    path:
      required: true
      example: "/config/home_upkeep_import"
      selector:
        text:
